use metro_cdmx;

CREATE TABLE IF NOT EXISTS `lines`(
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT, 
  `name` VARCHAR(255) NOT NULL,
  `color` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id)
)
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stations`(
`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(255) NOT NULL,
`line_id` BIGINT(20) UNSIGNED NOT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

PRIMARY KEY (id),
FOREIGN KEY (`line_id`) REFERENCES `lines`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
)
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `routes`(
`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`origin_station_id` BIGINT(20) UNSIGNED NOT NULL,
`destination_station_id` BIGINT(20) UNSIGNED NOT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

PRIMARY KEY (id),
FOREIGN KEY (`origin_station_id`) REFERENCES `stations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (`destination_station_id`) REFERENCES `stations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
)
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `schedules`(
`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`route_id` BIGINT(20) UNSIGNED NOT NULL,
`departure_time` TIME NOT NULL,
`arrival_time` TIME NOT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
FOREIGN KEY (`route_id`) REFERENCES `routes`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
)
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

